### ISSUE TITLE
how can i trans  the C to the gcode

### ISSUE THREAD

**Issue by hz805568** [o0morgan0o/gcode-generative-for-processing#1]
Hello, I juset want to know how to translate the Ccde output the gcode to 3D printer，Please tell me ，tks

**Comment by o0morgan0o** [comment]
Once you have a Gcode file you just need to send it to your printer via your SD card ,or use any software which can communicates with the printer likte pronterface or any octoprint server. I am not sure to understand your question.

**Comment by o0morgan0o** [comment]
Please see this https://github.com/o0morgan0o/gcode-generative-for-processing/issues/2, may be it will answer to your problem. Thank you
