### ISSUE TITLE
Troubles with installation

### ISSUE THREAD

**Issue by 0000marcosg** [o0morgan0o/gcode-generative-for-processing#2]
Hi! Im having troubles installing the library, I cant get Porcessing to find it. And I cant find in this repository the file structure that Processing uses to read the libraries.

Cool project, by the way. Thank you!

**Comment by o0morgan0o** [comment]
Thank you for your kind words. You are right, sorry i am still learning the JAVA way of handling libraries. This repo is the source code, Processing need the compiled library. I added the link in the installation instructions. The compiled project is here : https://github.com/o0morgan0o/gcodeGenerative . Hope it works.

**Comment by 0000marcosg** [comment]
Thank you! I just tested it and run as expected.
